[project]
name = "sata"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.2.0",
    "langgraph>=1.0.8",
    "pandas>=3.0.0",
    "pysqlite3>=0.6.0",
]
